Split in source files, add color chooser, format output, introduce localisation support

diff --git a/XUiDesigner/Makefile b/XUiDesigner/Makefile
--- a/XUiDesigner/Makefile
+++ b/XUiDesigner/Makefile
@@ -1,42 +1,141 @@
 
+	# check CPU and supported optimization flags
+	ifeq ($(UNAME), Linux)
+		ifneq ($(shell cat /proc/cpuinfo | grep sse3 ) , )
+			SSE_CFLAGS = -msse3 -mfpmath=sse
+		else ifneq ($(shell cat /proc/cpuinfo | grep sse2 ) , )
+			SSE_CFLAGS = -msse2 -mfpmath=sse
+		else ifneq ($(shell cat /proc/cpuinfo | grep sse ) , )
+			SSE_CFLAGS = -msse -mfpmath=sse
+			else ifneq ($(shell cat /proc/cpuinfo | grep ARM ) , )
+			ifneq ($(shell cat /proc/cpuinfo | grep ARMv7 ) , )
+				ifneq ($(shell cat /proc/cpuinfo | grep vfpd32 ) , )
+					SSE_CFLAGS = -march=armv7-a -mfpu=vfpv3 
+				else ifneq ($(shell cat /proc/cpuinfo | grep vfpv3 ) , )
+					SSE_CFLAGS = -march=armv7-a -mfpu=vfpv3
+				endif
+			else
+				ARMCPU = "YES"
+			endif
+		else
+			SSE_CFLAGS =
+		endif
+	endif
+
+	# set bundle name
+	NAME = XUiDesigner
+	EXEC_NAME  = $(shell echo $(NAME) | tr A-Z a-z)
+	BUILD_DIR = build
+	VER = 1.5
 
 	LIB_DIR := ../libxputty/libxputty/
 	HEADER_DIR := $(LIB_DIR)include/
+	LOCALIZE_DIR := ../libxputty/xputty/dialogs/
+	PREFIX ?= /usr
+	BIN_DIR ?= $(PREFIX)/bin
+	SHARE_DIR ?= $(PREFIX)/share
+	DESKAPPS_DIR ?= $(SHARE_DIR)/applications
+	PIXMAPS_DIR ?= $(SHARE_DIR)/pixmaps
+	MAN_DIR ?= $(SHARE_DIR)/man/man1
+	LOCAL_DIR ?= $(SHARE_DIR)/locale
 
-	# include path for library headers
-	INCLUDES := -I. -I$(HEADER_DIR) 
-	# link flags to dynamic link cairo and X11 (default)
-	LDFLAGS += -fPIC -Wl,-z,noexecstack -Wl,--no-undefined `pkg-config --cflags --libs cairo x11 lilv-0` -lm
+	# set compile flags
+	LDFLAGS += -fPIC -Wl,-z,noexecstack -Wl,--no-undefined -I./ -I../libxputty/libxputty/include/ \
+	`pkg-config --cflags --libs cairo x11 lilv-0` -lm
 	CXXFLAGS += -O2 -D_FORTIFY_SOURCE=2 -Wall -fstack-protector `pkg-config lilv-0 --cflags` 
 	DEBUG_CXXFLAGS += -g -D DEBUG
-
+	# invoke build files
+	OBJECTS = $(wildcard *.c)
+	LOCALIZE = $(LOCALIZE_DIR)xfile-dialog.c $(LOCALIZE_DIR)xmessage-dialog.c $(LOCALIZE_DIR)xsavefile-dialoge.c
+	## output style (bash colours)
 	BLUE = "\033[1;34m"
 	RED =  "\033[1;31m"
 	NONE = "\033[0m"
 
-	XUIDESIGNER_SOURCES := $(wildcard *.c)
-	XUIDESIGNER_OBJ := $(patsubst %.c,%.o,$(XUIDESIGNER_SOURCES))
-	EXEC_FILES := $(patsubst %.c,%,$(XUIDESIGNER_SOURCES))
+.PHONY : $(HEADER_DIR)*.h all debug nls gettext updatepot po clean install uninstall 
 
-.PHONY : all clean
-
-all: $(EXEC_FILES) 
+all : check $(NAME)
+	@mkdir -p ./$(BUILD_DIR)
+	@mv ./$(EXEC_NAME) ./$(BUILD_DIR)
+	@if [ -f ./$(BUILD_DIR)/$(EXEC_NAME) ]; then echo $(BLUE)"build finish, now run make install"; \
+	else echo $(RED)"sorry, build failed"; fi
+	@echo $(NONE)
 
 debug: CXXFLAGS = $(DEBUG_CXXFLAGS) 
 debug: all
 
-clean:
-	rm -f $(XUIDESIGNER_OBJ) $(EXEC_FILES)
+nls: LDFLAGS += -DENABLE_NLS -DGETTEXT_PACKAGE=\"$(EXEC_NAME)\" -DLOCAL_DIR=\"$(LOCAL_DIR)\"
+nls: gettext all 
 
-$(HEADER_DIR)*.h:
-	@echo $(RED)You need to build libxputty before build XFileSelet!!$(NONE)
-	@echo $(RED)Just build from the top directory to keep the order$(NONE)
-	@exit 1
+    #@localisation
+MSGLANGS=$(notdir $(wildcard po/*po))
+MSGOBJS=$(addprefix locale/,$(MSGLANGS:.po=/LC_MESSAGES/$(EXEC_NAME).mo))
+LANGS=$(addprefix locale/,$(MSGLANGS:.po=/LC_MESSAGES/))
+LANGW=$(words  $(MSGLANGS))
 
-$(XUIDESIGNER_OBJ): $(XUIDESIGNER_SOURCES) $(HEADER_DIR)*.h
-	$(CC) -c $(patsubst %.o,%.c,$@) -o $@  $(INCLUDES) $(LDFLAGS)
+gettext: $(MSGOBJS)
 
-$(EXEC_FILES): $(XUIDESIGNER_OBJ)
-	$(CC) $(CXXFLAGS) -Wall $(patsubst %,%.c,$@) -L. $(LIB_DIR)libxputty.a -o $@  $(INCLUDES) $(LDFLAGS)
+locale/%/LC_MESSAGES/$(EXEC_NAME).mo: po/%.po
+	mkdir -p $(dir $@)
+	msgfmt -c -o $@ po/$*.po
 
+updatepot:
+	@mkdir -p ./po/
+	xgettext --keyword=_ --language=C++ --add-comments --sort-output --package-name=$(EXEC_NAME) --package-version=$(VER) -o po/$(EXEC_NAME).pot $(OBJECTS) $(LOCALIZE)
+	for POFILE in $(MSGLANGS) ; do msgmerge --update po/$$POFILE po/$(EXEC_NAME).pot ; done
 
+po:
+	msginit --input=po/$(EXEC_NAME).pot --locale=$(LANG) --output=po/$(basename $(LANG)).po
+	echo $(LANG)
+
+check :
+ifdef ARMCPU
+	@echo $(RED)ARM CPU DEDECTED, please check the optimization flags
+	@echo $(NONE)
+endif
+
+clean :
+	@rm -f ./$(BUILD_DIR)/$(EXEC_NAME)
+	@rm -rf ./$(BUILD_DIR)
+	@echo ". ." $(BLUE)", clean up"$(NONE)
+
+install :
+ifneq ("$(wildcard ./$(BUILD_DIR))","")
+	mkdir -p $(DESTDIR)$(BIN_DIR)
+	cp ./$(BUILD_DIR)/$(EXEC_NAME) $(DESTDIR)$(BIN_DIR)/$(EXEC_NAME)
+	mkdir -p $(DESTDIR)$(DESKAPPS_DIR)
+	cp $(NAME).desktop $(DESTDIR)$(DESKAPPS_DIR)
+	mkdir -p $(DESTDIR)$(PIXMAPS_DIR)
+	cp $(NAME).png $(DESTDIR)$(PIXMAPS_DIR)
+	@if [ ${LANGW} -gt 1 ]; then \
+		for lang in $(LANGS) ; \
+		do \
+			if [ -f $$lang/$(EXEC_NAME).mo ]; then \
+				mkdir -p $(DESTDIR)$(SHARE_DIR)/$$lang; \
+				cp $$lang/$(EXEC_NAME).mo $(DESTDIR)$(SHARE_DIR)/$$lang; \
+			fi \
+		done \
+	elif [ ${LANGW} -gt 0 ]; then \
+			if [ -f $(LANGS)/$(EXEC_NAME).mo ]; then \
+				mkdir -p $(DESTDIR)$(SHARE_DIR)/$(LANGS); \
+				cp $(LANGS)/$(EXEC_NAME).mo $(DESTDIR)$(SHARE_DIR)/$(LANGS); \
+			fi \
+	fi
+	update-desktop-database || true
+	@echo ". ." $(BLUE)", done"$(NONE)
+else
+	@echo ". ." $(BLUE)", you must build first"$(NONE)
+endif
+
+uninstall :
+	@rm -rf $(DESTDIR)$(BIN_DIR)/$(EXEC_NAME)
+	@rm -rf $(DESTDIR)$(DESKAPPS_DIR)/$(NAME).desktop
+	@rm -rf $(DESTDIR)$(PIXMAPS_DIR)/$(NAME).png
+	@rm -rf $(addprefix $(SHARE_DIR)/, $(MSGOBJS))
+	@echo ". ." $(BLUE)", done"$(NONE)
+
+$(NAME) :
+	$(CC) $(CXXFLAGS) $(OBJECTS) -L. ../libxputty/libxputty/libxputty.a -o $(EXEC_NAME) $(LDFLAGS)
+
+doc:
+	#pass
